### ISSUE TITLE
Homebridge 1.01 breaks plugin

### ISSUE THREAD

**Issue by swamplynx** [aphex3k/homebridge-bloomsky#17]
Homebridge 1.0.1 appears to break this plugin. I've tried fully removing and clearing the persistant accessory.

[4/27/2020, 12:32:12 PM] [Bloomsky] registerNewAccessories
[4/27/2020, 12:32:12 PM] [Bloomsky] stationNeedsToBeRegistered: [object Object]
[4/27/2020, 12:32:12 PM] [Bloomsky] Add Accessory: 442C05BC9BE8
[4/27/2020, 12:32:12 PM] [Bloomsky] FFMPEG constructor
[4/27/2020, 12:32:12 PM] [Bloomsky] Debug loggin enabled...
[4/27/2020, 12:32:12 PM] [Bloomsky] createCameraControlService
[4/27/2020, 12:32:12 PM] [Bloomsky] _createStreamControllers
[4/27/2020, 12:32:12 PM] [Bloomsky] adding StreamController #1/1
[4/27/2020, 12:32:12 PM] [Bloomsky] 1/1 stream controllers registered
[4/27/2020, 12:32:12 PM] [Bloomsky] 0000003E-0000-1000-8000-0026BB765291
[4/27/2020, 12:32:12 PM] [Bloomsky] 00000110-0000-1000-8000-0026BB765291.0
[4/27/2020, 12:32:12 PM] [Bloomsky] 00000111-0000-1000-8000-0026BB765291
[4/27/2020, 12:32:12 PM] [Bloomsky] Error: Camera Control Service Registration failed... +1
    at Bloomsky.addAccessory (/usr/lib/node_modules/homebridge-bloomsky/lib/Bloomsky.js:170:19)
    at Bloomsky.registerNewAccessories (/usr/lib/node_modules/homebridge-bloomsky/lib/Bloomsky.js:395:22)
    at Bloomsky.<anonymous> (/usr/lib/node_modules/homebridge-bloomsky/lib/Bloomsky.js:348:44)
    at step (/usr/lib/node_modules/homebridge-bloomsky/lib/Bloomsky.js:32:23)
    at Object.next (/usr/lib/node_modules/homebridge-bloomsky/lib/Bloomsky.js:13:53)
    at fulfilled (/usr/lib/node_modules/homebridge-bloomsky/lib/Bloomsky.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by santheman-nl** [comment]
Yes, I have the same message.
I hope it can be solved?

**Comment by santheman-nl** [comment]
@aphex3k do you think you have time to look into this?

**Comment by aphex3k** [comment]
I have not updated to homebridge 1.01 yet...

**Comment by santheman-nl** [comment]
@aphex3k Will you be able to do so?

**Comment by aphex3k** [comment]
@swamplynx @santheman-nl , can you please test version `https://www.npmjs.com/package/homebridge-bloomsky/v/1.2.0-alpha.0`?

**Comment by swamplynx** [comment]
@aphex3k , thanks much for rewriting. I’m able to load the new plugin, and the measurements come through, but getting the below for video. This may be due to my specific Pi configuration and haven’t done any debugging yet. Will let you know what if find. Using libx264. 

EDIT: Thumbnails are working, but video isn’t. Will let you know what I find. 

![25492F3D-E6F3-4F4B-B8F6-36563070CA53](https://user-images.githubusercontent.com/13987471/82630045-917a6d80-9bbf-11ea-9b8c-93ef7e85f9fb.png)

**Comment by aphex3k** [comment]
Do you get the same picture for the snapshot?

**Comment by aphex3k** [comment]
Also, can you double-check that ffmpeg was compiled with http protocol support?

**Comment by swamplynx** [comment]
Snapshot works perfectly. Capturing logs now. The ffmpeg compile could be the issue since I just used the Wheezey apt build, but have no issues with my Ring integration that I imagine also uses HTTP (or perhaps just RTP).

**Comment by swamplynx** [comment]
Humm... Oddly now it seems to be working. Just rather on the slow side. Seems to be hanging for a bit loading libpostproc or querying AWS?

Starting video stream (1280x720, 30 fps, 299 kbps, 1378 mtu)...
FFMPEG command: ffmpeg -loop 1 -i http://s3-us-west-1.amazonaws.com/bskyimgs/faBiuZWsp6StqqqqqJ1lr5WolZmqoJw=.jpg -map 0:0 -c:v libx264 -pix_fmt yuv420p -r 30 -an -sn -dn -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 16277813 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params OIX6x+mpjin/2jglf0HZPHOJHnp1IT+5Ir/JtOR2 srtp://192.168.123.47:49162?rtcpport=49162&localrtcpport=49162&pkt_size=1378
FFMPEG: received first frame
VIDEO: ffmpeg version 4.1.5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --disable-decoder=amrnb --disable-decoder=libopenjpeg --disable-libopencv --disable-outdev=sdl2 --disable-podpages --disable-sndio --disable-stripping --enable-libaom --enable-avfilter --enable-avresample --enable-gcrypt --disable-gnutls --enable-openssl --enable-gpl --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libkvazaar --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx265 --enable-libzimg --enable-libxvid --enable-libzvbi --enable-nonfree --enable-opencl --enable-opengl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --enable-libwebp --incdir=/usr/include/arm-linux-gnueabihf --libdir=/usr/lib/arm-linux-gnueabihf --prefix=/usr --toolchain=hardened --enable-frei0r --enable-chromaprint --enable-libx264 --enable-libiec61883 --enable-libdc1394 --disable-altivec --shlibdir=/usr/lib/arm-linux-gnueabihf
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100

VIDEO:   libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

VIDEO: Input #0, image2, from 'http://s3-us-west-1.amazonaws.com/bskyimgs/faBiuZWsp6StqqqqqJ1lr5WolZmqoJw=.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 13024 kb/s
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 640x640, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help

VIDEO: [swscaler @ 0x10e8af0] 
VIDEO: deprecated pixel format used, make sure you did set range correctly

VIDEO: [libx264 @ 0x970650] using cpu capabilities: ARMv6 NEON

VIDEO: [libx264 @ 0x970650] profile High, level 3.1, 4:2:0, 8-bit

VIDEO: Output #0, rtp, to 'srtp://192.168.123.47:49162?rtcpport=49162&localrtcpport=49162&pkt_size=1378':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 640x640, q=-1--1, 299 kb/s, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.35.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 299000/0/299000 buffer size: 598000 vbv_delay: -1

VIDEO: frame=   15 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A dup=2 drop=0 speed=   0x    
VIDEO: frame=   32 fps= 31 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A dup=5 drop=0 speed=   0x    
VIDEO: frame=   48 fps= 29 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A dup=8 drop=0 speed=   0x    
VIDEO: frame=   63 fps= 29 q=21.0 size=      47kB time=00:00:00.33 bitrate=1166.1kbits/s dup=10 drop=0 speed=0.154x    
VIDEO: frame=   78 fps= 29 q=26.0 size=      57kB time=00:00:00.83 bitrate= 560.0kbits/s dup=13 drop=0 speed=0.31x    
VIDEO: frame=   93 fps= 29 q=26.0 size=      69kB time=00:00:01.33 bitrate= 426.1kbits/s dup=15 drop=0 speed=0.412x    
VIDEO: frame=   96 fps= 25 q=25.0 size=      73kB time=00:00:01.43 bitrate= 415.2kbits/s dup=16 drop=0 speed=0.366x    
VIDEO: frame=   98 fps= 21 q=25.0 size=      73kB time=00:00:01.50 bitrate= 398.6kbits/s dup=16 drop=0 speed=0.325x    
VIDEO: frame=  101 fps= 19 q=26.0 size=      77kB time=00:00:01.60 bitrate= 392.0kbits/s dup=17 drop=0 speed=0.302x    
VIDEO: frame=  103 fps= 17 q=24.0 size=      77kB time=00:00:01.66 bitrate= 377.5kbits/s dup=17 drop=0 speed=0.28x    
VIDEO: frame=  105 fps= 16 q=25.0 size=      80kB time=00:00:01.73 bitrate= 378.8kbits/s dup=17 drop=0 speed=0.26x    
VIDEO: frame=  108 fps= 15 q=24.0 size=      84kB time=00:00:01.83 bitrate= 373.7kbits/s dup=18 drop=0 speed=0.249x    
Received (unsupported) request to reconfigure to: {"width":640,"height":360,"fps":30,"max_bit_rate":132,"rtcp_interval":0.5}
VIDEO: frame=  110 fps= 14 q=24.0 size=      84kB time=00:00:01.90 bitrate= 362.1kbits/s dup=18 drop=0 speed=0.237x    
VIDEO: frame=  113 fps= 13 q=25.0 size=      88kB time=00:00:02.00 bitrate= 359.1kbits/s dup=19 drop=0 speed=0.229x    
VIDEO: frame=  115 fps= 12 q=23.0 size=      88kB time=00:00:02.06 bitrate= 348.8kbits/s dup=19 drop=0 speed=0.219x    
VIDEO: frame=  117 fps= 12 q=24.0 size=      92kB time=00:00:02.13 bitrate= 351.6kbits/s dup=19 drop=0 speed=0.211x    
VIDEO: frame=  120 fps= 11 q=23.0 size=      96kB time=00:00:02.23 bitrate= 350.4kbits/s dup=20 drop=0 speed=0.207x    
VIDEO: frame=  122 fps= 11 q=23.0 size=      96kB time=00:00:02.30 bitrate= 341.5kbits/s dup=20 drop=0 speed= 0.2x    
VIDEO: frame=  125 fps= 10 q=24.0 size=     100kB time=00:00:02.40 bitrate= 340.5kbits/s dup=21 drop=0 speed=0.197x    
VIDEO: frame=  127 fps=9.9 q=22.0 size=     100kB time=00:00:02.46 bitrate= 332.3kbits/s dup=21 drop=0 speed=0.192x    
VIDEO: frame=  129 fps=9.5 q=24.0 size=     104kB time=00:00:02.53 bitrate= 336.1kbits/s dup=21 drop=0 speed=0.188x    
VIDEO: frame=  132 fps=9.3 q=22.0 size=     108kB time=00:00:02.63 bitrate= 336.6kbits/s dup=22 drop=0 speed=0.186x    
VIDEO: frame=  134 fps=9.0 q=22.0 size=     109kB time=00:00:02.70 bitrate= 329.4kbits/s dup=22 drop=0 speed=0.182x    
VIDEO: frame=  137 fps=8.8 q=23.0 size=     113kB time=00:00:02.80 bitrate= 329.1kbits/s dup=23 drop=0 speed=0.18x    
VIDEO: frame=  139 fps=8.6 q=22.0 size=     113kB time=00:00:02.86 bitrate= 322.4kbits/s dup=23 drop=0 speed=0.177x    
VIDEO: frame=  141 fps=8.3 q=23.0 size=     117kB time=00:00:02.93 bitrate= 326.4kbits/s dup=23 drop=0 speed=0.173x    
VIDEO: frame=  144 fps=8.2 q=22.0 size=     121kB time=00:00:03.03 bitrate= 327.3kbits/s dup=24 drop=0 speed=0.172x    
VIDEO: frame=  146 fps=8.0 q=22.0 size=     122kB time=00:00:03.10 bitrate= 321.1kbits/s dup=24 drop=0 speed=0.169x    
VIDEO: frame=  149 fps=7.9 q=23.0 size=     125kB time=00:00:03.20 bitrate= 321.2kbits/s dup=25 drop=0 speed=0.169x    
VIDEO: frame=  151 fps=7.7 q=21.0 size=     126kB time=00:00:03.26 bitrate= 315.4kbits/s dup=25 drop=0 speed=0.166x    
VIDEO: frame=  153 fps=7.5 q=22.0 size=     130kB time=00:00:03.33 bitrate= 318.8kbits/s dup=25 drop=0 speed=0.164x    
VIDEO: frame=  156 fps=7.4 q=21.0 size=     134kB time=00:00:03.43 bitrate= 320.6kbits/s dup=26 drop=0 speed=0.163x    
VIDEO: frame=  158 fps=7.3 q=21.0 size=     135kB time=00:00:03.50 bitrate= 315.2kbits/s dup=26 drop=0 speed=0.161x    
VIDEO: frame=  161 fps=7.2 q=22.0 size=     139kB time=00:00:03.60 bitrate= 316.2kbits/s dup=27 drop=0 speed=0.161x    
Stopped streaming session!

**Comment by santheman-nl** [comment]
Still nog succes unfortunately....
I get the same "test screen" while my Ring and DLink cam are working fine.
I added this to config:
        {
            "name": "Bloomsky",
            "apiKey": "=====myapi==========",
            "apiUrl": "https://api.bloomsky.com/api/skydata/",
            "vcodec": "h264_omx",
            "debug": false,
            "platform": "Bloomsky"
        }
But when I go to plugin settings, I need to fill in a name... by default that adds: 
        {
            "name": "Example Dynamic Platform",
            "platform": "ExampleHomebridgePlugin"
        }
To config.

**Comment by santheman-nl** [comment]
SNAPSHOT: Input #0, image2, from 'http://s3-us-west-1.amazonaws.com/bskyimgs/faBiuZWsnpapoKq0qJ1lr5WomJekm5U=.jpg':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 15006 kb/s

SNAPSHOT:     Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 640x640, 25 fps, 25 tbr, 25 tbn, 25 tbc

SNAPSHOT: Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> mjpeg (native))
Press [q] to stop, [?] for help

SNAPSHOT: Output #0, mjpeg, to 'pipe:':
  Metadata:
    encoder         : Lavf58.20.100

SNAPSHOT:     Stream #0:0: Video: mjpeg, yuvj422p(pc), 640x640, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.35.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1

SNAPSHOT: frame=    1 fps=0.0 q=4.4 Lsize=      40kB time=00:00:00.04 bitrate=8148.2kbits/s speed=0.574x    
video:40kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

Successfully captured snapshot at 480x270
Starting video stream (1280x720, 30 fps, 299 kbps, 1378 mtu)...
FFMPEG command: ffmpeg -loop 1 -i http://s3-us-west-1.amazonaws.com/bskyimgs/faBiuZWsnpapoKq0qJ1lr5WomJekm5U=.jpg -map 0:0 -c:v libx264 -pix_fmt yuv420p -r 30 -an -sn -dn -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 1920557 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params YRcyc6hSpgFbBw2n0taqkDapIFOFsAm1L+7dWkzG srtp://192.168.2.183:56862?rtcpport=56862&localrtcpport=56862&pkt_size=1378
FFMPEG: received first frame
VIDEO: ffmpeg version 4.1.4-1+rpt7~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
  configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --libdir=/usr/lib/arm-linux-gnueabihf --cpu=arm1176jzf-s --arch=arm

VIDEO:   WARNING: library configuration mismatch
  avutil      configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avcodec     configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avformat    configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avdevice    configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avfilter    configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  avresample  configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swscale     configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  swresample  configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  postproc    configuration: --prefix=/usr --extra-version='1+rpt7~deb10u1' --toolchain=hardened --incdir=/usr/include/arm-linux-gnueabihf --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-omx-rpi --enable-mmal --enable-neon --enable-rpi --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --libdir=/usr/lib/arm-linux-gnueabihf/neon/vfp --cpu=cortex-a7 --arch=armv6t2 --disable-thumb --enable-shared --disable-doc --disable-programs
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100

Stopped streaming session!
[Video] ffmpeg exited with code: null and signal: SIGKILL (Video stream stopped!)

**Comment by santheman-nl** [comment]
When changing the 264 name it makes one snapshot, but it doesn't refresh it. And the stream is not working.

**Comment by aphex3k** [comment]
the test screen is showing because homekit is asking for a snapshot picture before homebridge had the chance to go and fetch data about the camera. It should be gone on the next refresh. However, it seems like your plugin is not refreshing.
